//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maetsilor {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Classe de ressource fortement typée destinée, entre autres, à la recherche de chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resource() {
        }
        
        /// <summary>
        ///    Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maetsilor.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///    les recherches de ressources utilisant cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Recherche une chaîne localisée similaire à About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Recherche une chaîne localisée similaire à Maetsilor is an assistance software for tabletop role playing games. It gives the tools to be able to play online..
        /// </summary>
        public static string AboutDetails {
            get {
                return ResourceManager.GetString("AboutDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Recherche une chaîne localisée similaire à This site is about the Maetsilor project, a remake of the open-source project .
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Recherche une chaîne localisée similaire à Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Recherche une chaîne localisée similaire à Don&apos;t do this again &gt;:(.
        /// </summary>
        public static string ErrorDont {
            get {
                return ResourceManager.GetString("ErrorDont", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Recherche une chaîne localisée similaire à An error occurred while processing your request..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Recherche une chaîne localisée similaire à Completed functionalities.
        /// </summary>
        public static string FunctCompleted {
            get {
                return ResourceManager.GetString("FunctCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Recherche une chaîne localisée similaire à Functionalities in prodution.
        /// </summary>
        public static string FunctInProduction {
            get {
                return ResourceManager.GetString("FunctInProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Recherche une chaîne localisée similaire à Released functionalities.
        /// </summary>
        public static string FunctReleased {
            get {
                return ResourceManager.GetString("FunctReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Recherche une chaîne localisée similaire à Functionalities to develop.
        /// </summary>
        public static string FunctToDo {
            get {
                return ResourceManager.GetString("FunctToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Recherche une chaîne localisée similaire à Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Recherche une chaîne localisée similaire à Home page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Recherche une chaîne localisée similaire à Programmers.
        /// </summary>
        public static string Programmers {
            get {
                return ResourceManager.GetString("Programmers", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Recherche une chaîne localisée similaire à Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
    }
}
